name: Build and Test

on:
  pull_request:
  push:
    paths:
      - '**.js'
      - '**.js.snap'
      - '.github/workflows/*'

jobs:
  build:
    name: 'Run Tests'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js 12
        uses: actions/setup-node@v1.2.0
        with:
          node-version: '12'

      - name: Install Project
        run: yarn install --frozen-lockfile

      # skip until localization can be re-setup
      # - name: Generate Templates
      # run: node ./internals/scripts/generate-templates-for-linting

      - name: Run Tests
        run: yarn test:cov --maxWorkers=4

      - name: Build
        run: yarn build

      - name: Upload Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
