name: CharlieCarsonKids

on:
  pull_request:
  push:
    paths:
      - '**.js'
      - '**.js.snap'
      - '.github/workflows/*'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Determine Yarn Cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules
        uses: actions/cache@v1.0.3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Setup Node.js 12
        uses: actions/setup-node@v1.2.0
        with:
          node-version: '12'

      - name: Install Dependencies
        run: yarn install

      - name: Build Site
        run: yarn build

      - name: Run Tests
        run: yarn test:cov --maxWorkers=4

      - name: Upload Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  snapshots:
    name: Compare Snapshots
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2

      - name: Determine Yarn Cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules
        uses: actions/cache@v1.0.3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Setup Node.js 12
        uses: actions/setup-node@v1.2.0
        with:
          node-version: '12'

      - name: Install Dependencies
        run: yarn install

      - name: Upload Snapshots
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        uses: percy/storybook-action@v0.1.2
        with:
          custom-command: 'yarn snapshot'
