name: Build and Test

on: [push, pull_request]

jobs:
  build:
    name: 'Run Tests'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js 12
        uses: actions/setup-node@v1.2.0
        with:
          node-version: '12'

      - name: Install Dependencies
        run: sudo apt-get install -y autoconf

      - name: Install Package
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: install

      - name: Generate Templates
        run: node ./internals/scripts/generate-templates-for-linting

      - name: Run Tests
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: test:cov --maxWorkers=4

      - name: Build
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: build

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
